name: Goldbach-CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r app/requirements.txt &

      - name: flake8 Lint
        uses: py-actions/flake8@v2

      - name: Run unit tests
        run: pytest &

      - name: Debug
        run: pwd & ls

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test artifacts
        run: touch testing.txt

      - name: Test ls
        run: ls
#      - name: Semantic Release
#        uses: docker://semanticrelease/semantic-release:latest
#        with:
#          entrypoint: /bin/sh
#          args: |
#            npm install --save-dev @semantic-release/git @semantic-release/changelog
#            npx semantic-release --publish --no-ci
#            echo -n "$(git describe --tags | tr -d "\n") > version.txt
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DOCKER_HUB_USERNAME: ${docker_hub_username}
#          GH_REPOSITORY_NAME: ${github_repository_name}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: |
#            ${docker_hub_username}/${docker_image_name}:${{ github.ref }}
#            ${docker_hub_username}/${docker_image_name}}:latest
#
#      - name: Update README.md with Docker image tag
#        run: |
#          sed -i "s/<DOCKER_IMAGE_TAG>/${{ github.ref }}/g" README.md
#
#      - name: Commit and push changes
#        run: |
#          git config --global user.email "terraform@example.com"
