---
apiVersion: v1
kind: Service
metadata:
  name: goldbach
spec:
  selector:
    app: goldbach
  ports:
    - name: http
      port: 80
      targetPort: 11000
    - name: https
      port: 443
      targetPort: 11000
